#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.18033
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChiroAppDev.Resource", IsApplication=true)]

namespace ChiroAppDev
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040001
			public const int faqs = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int groepen_array = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int tab_dev = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int tab_faq = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tab_main = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int tab_settings = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int tab_sos_blue = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int tab_sos_red = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int Image = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int Text = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Text1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Text2 = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int antigifcentrum = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int apotheek = 2131165191;
			
			// aapt resource value: 0x7f070011
			public const int autocomplete_groep = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int chiroLabel = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int faqBackButton = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int faqList = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int faqText = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int faqTitle = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int hulpdiensten = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int infoText = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int myButton = 2131165203;
			
			// aapt resource value: 0x7f07000e
			public const int naamField = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int naamLabel = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int politie = 2131165189;
			
			// aapt resource value: 0x7f070012
			public const int saveButton = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int textView2 = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int textView5 = 2131165200;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Emergency = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FAQ = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int faq_detail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int list_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Settings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Tabbed = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int na18u = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int voor18u = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_Light = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
